class SignUpLogInClass {
  int? users_customers_id;
  String? one_signal_id,
      users_customers_type,
      first_name,
      last_name,
      phone,
      email,
      password,
      profile_pic,
      proof_document,
      valid_document,
      messages,
      notifications,
      account_type,
      social_acc_type,
      google_access_token,
      verify_code,
      verified_badge,
      date_expiry,
      date_added,
      status;

  SignUpLogInClass({
    this.status,
    this.date_added,
    this.profile_pic,
    this.first_name,
    this.last_name,
    this.password,
    this.users_customers_id,
    this.phone,
    this.account_type,
    this.date_expiry,
    this.email,
    this.google_access_token,
    this.messages,
    this.notifications,
    this.one_signal_id,
    this.proof_document,
    this.social_acc_type,
    this.users_customers_type,
    this.valid_document,
    this.verified_badge,
    this.verify_code,
  });

  Map<String, dynamic> toMap() {
    return {
      'users_customers_id': users_customers_id,
      'one_signal_id': one_signal_id,
      'users_customers_type': users_customers_type,
      'first_name': first_name,
      'last_name': last_name,
      'phone': phone,
      'email': email,
      'password': password,
      'profile_pic': profile_pic,
      'proof_document': proof_document,
      'valid_document': valid_document,
      'messages': messages,
      'notifications': notifications,
      'account_type': account_type,
      'social_acc_type': social_acc_type,
      'google_access_token': google_access_token,
      'verify_code': verify_code,
      'verified_badge': verified_badge,
      'date_expiry': date_expiry,
      'date_added': date_added,
      'status': status,
    };
  }

  factory SignUpLogInClass.fromMap(Map<String, dynamic> map) {
    return SignUpLogInClass(
      users_customers_id: map['users_customers_id'] ?? -1,
      one_signal_id: map['one_signal_id'] ?? '',
      users_customers_type: map['users_customers_type'] ?? '',
      first_name: map['first_name'] ?? '',
      last_name: map['last_name'] ?? '',
      phone: map['phone'] ?? '',
      email: map['email'] ?? '',
      password: map['password'] ?? '',
      profile_pic: map['profile_pic'] ?? '',
      proof_document: map['proof_document'] ?? '',
      valid_document: map['valid_document'] ?? '',
      messages: map['messages'] ?? '',
      notifications: map['notifications'] ?? '',
      account_type: map['account_type'] ?? '',
      social_acc_type: map['social_acc_type'] ?? '',
      google_access_token: map['google_access_token'] ?? '',
      verify_code: map['verify_code'] ?? '',
      verified_badge: map['verified_badge'] ?? '',
      date_expiry: map['date_expiry'] ?? '',
      date_added: map['date_added'] ?? '',
      status: map['status'] ?? '',
    );
  }
}
